# Generated by Django 5.0.1 on 2024-02-16 12:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_name_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Имя'),
        ),
    ]
