# Generated by Django 5.0.1 on 2024-02-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.TextField(blank=True, verbose_name='Имя'),
        ),
    ]
