# Generated by Django 5.0.1 on 2024-03-03 10:39

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', tinymce.models.HTMLField(max_length=225, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, verbose_name='Заголовок')),
                ('description', tinymce.models.HTMLField(max_length=1000, null=True, verbose_name='Описание')),
                ('content', models.ImageField(upload_to='', verbose_name='Контент')),
                ('type_conten', models.CharField(choices=[('public', 'Публичный'), ('privat', 'Приватный')], default='public', max_length=200, verbose_name='Аудитория')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='article.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
