# Generated by Django 5.0.1 on 2024-03-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_article_tag_tag_article_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='type_conten',
            new_name='type_content',
        ),
    ]
