# Generated by Django 5.0.1 on 2024-02-14 15:51

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='article.tag', verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=tinymce.models.HTMLField(max_length='225', verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=tinymce.models.HTMLField(max_length=225, verbose_name='Тег'),
        ),
    ]
