# Generated by Django 5.0.1 on 2024-02-14 16:13

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_tag_alter_article_title_alter_tag_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='tag_name',
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание'),
        ),
    ]
