# Generated by Django 5.0.1 on 2024-02-16 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_options_rename_tag_tag_tag_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='article.tag', verbose_name='Тег'),
        ),
    ]
