# Generated by Django 5.0.1 on 2024-03-31 12:15

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_remove_article_tag_comment_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Создатель'), (2, 'Куратор'), (3, 'Модер'), (4, 'Член сообщества')], default=4, verbose_name='Роль')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='replys',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='article.tag', verbose_name='Тег'),
        ),
        migrations.AddField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Тело'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='article.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=tinymce.models.HTMLField(max_length=30, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', tinymce.models.HTMLField(max_length=25, verbose_name='Название Сообщства')),
                ('description_of_group', tinymce.models.HTMLField(max_length=500, verbose_name='Описание группы')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('role_member', models.ForeignKey(blank=True, default='BASIC', null=True, on_delete=django.db.models.deletion.CASCADE, to='article.rolegroup', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группа',
            },
        ),
    ]
