# Generated by Django 5.0.1 on 2024-03-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_comment_dislikes_comment_likes_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='location',
            field=models.IntegerField(default=0, verbose_name='Метоположение'),
        ),
    ]
