# Generated by Django 5.0.1 on 2024-03-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_article_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='location',
        ),
    ]
