# Generated by Django 5.0.1 on 2024-03-31 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_remove_article_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='RoleGroup',
        ),
    ]
