# Generated by Django 5.0.1 on 2024-04-01 10:08

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_delete_group_delete_rolegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Создатель'), (2, 'Куратор'), (3, 'Модер'), (4, 'Член сообщества')], default=4, verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='Group_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', tinymce.models.HTMLField(max_length=25, verbose_name='Название Сообщства')),
                ('description_of_group', tinymce.models.HTMLField(max_length=500, verbose_name='Описание группы')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('role_member', models.ForeignKey(blank=True, default='BASIC', null=True, on_delete=django.db.models.deletion.CASCADE, to='article.rolegroup', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группа',
            },
        ),
    ]
