# Generated by Django 5.0.1 on 2024-04-01 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_remove_article_likes_remove_article_replys_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_up',
            name='members_group',
        ),
        migrations.AddField(
            model_name='group_up',
            name='members',
            field=models.ManyToManyField(related_name='groups_joined', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
