# Generated by Django 5.0.1 on 2024-04-08 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_alter_comment_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_up',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups_joined', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
